import type { GraphEdgeRecord, GraphNodeRecord } from "../../kernel";
import { fixtureEdge, fixtureNode } from "../shared/fixture-graph";

const repository = "agent-core";

export const agentCoreNodes: readonly GraphNodeRecord[] = [
  fixtureNode({
    id: "deep-agent",
    kind: "agent",
    level: 2,
    owner: repository,
    label: "DeepAgent",
    subtitle: "outer orchestration",
    summary: "外层 Agent 生命周期，负责 invoke、任务编排与会话收尾。",
    repository,
    path: "openjiuwen/harness/deep_agent.py",
    symbol: "DeepAgent",
    position: { x: 250, y: 280 },
    renderer: "stage",
    expandable: true,
  }),
  fixtureNode({
    id: "react-loop",
    kind: "loop",
    level: 3,
    owner: repository,
    label: "ReActAgent",
    subtitle: "inner loop controller",
    summary:
      "DeepAgent 内部的 ReAct 循环控制器，负责组织 Context、模型决策、工具 observation 与下一轮迭代。",
    repository,
    path: "openjiuwen/core/single_agent/agents/react_agent.py",
    symbol: "ReActAgent",
    position: { x: 40, y: 110 },
    renderer: "stage",
    parentId: "deep-agent",
    expandable: true,
    viewProperties: { accent: "signal" },
  }),
  fixtureNode({
    id: "context",
    kind: "context",
    level: 4,
    owner: repository,
    label: "Context Engine",
    subtitle: "assemble window",
    summary: "组合 system、history、tool schema，并输出最终 ContextWindow。",
    repository,
    path: "openjiuwen/core/context_engine/context_engine.py",
    symbol: "ContextEngine",
    position: { x: 480, y: 280 },
    renderer: "stage",
    parentId: "deep-agent",
    expandable: true,
    viewProperties: { accent: "context" },
  }),
  fixtureNode({
    id: "model",
    kind: "model",
    level: 4,
    owner: repository,
    label: "Model Call",
    subtitle: "reason + generate",
    summary: "向模型发送最终上下文，接收文本或 tool_calls。",
    repository,
    path: "openjiuwen/core/foundation/llm/model.py",
    symbol: "Model",
    position: { x: 720, y: 155 },
    renderer: "stage",
    parentId: "deep-agent",
    expandable: true,
    viewProperties: { accent: "signal" },
  }),
  fixtureNode({
    id: "decision",
    kind: "decision",
    level: 4,
    owner: repository,
    label: "ReAct Decision",
    subtitle: "route next action",
    summary: "判断模型结果是结束响应、执行工具，还是进入下一轮 ReAct。",
    repository,
    path: "openjiuwen/core/single_agent/agents/react_agent.py",
    symbol: "ReActAgent",
    position: { x: 960, y: 280 },
    renderer: "stage",
    parentId: "deep-agent",
    expandable: true,
  }),
  fixtureNode({
    id: "tool",
    kind: "tool",
    level: 4,
    owner: repository,
    label: "Tool Runtime",
    subtitle: "execute + observe",
    summary: "执行工具调用，并把 observation 追加回上下文。",
    repository,
    path: "openjiuwen/core/single_agent/ability_manager.py",
    symbol: "AbilityManager",
    position: { x: 720, y: 440 },
    renderer: "stage",
    parentId: "deep-agent",
    expandable: true,
  }),
  fixtureNode({
    id: "rail-init",
    kind: "rail",
    level: 4,
    owner: repository,
    label: "Rail lifecycle",
    subtitle: "init / uninit",
    summary: "独立于运行 Hook 的初始化组；按优先级注册 Rail。",
    repository,
    path: "openjiuwen/harness/deep_agent.py",
    symbol: "DeepAgent",
    position: { x: 250, y: 20 },
    renderer: "rail",
    expandable: true,
    attributes: {
      lifecycle: "init",
      hooks: [
        { event: "SysOperationRail.init", priority: 100, namespace: "outer" },
        { event: "SkillUseRail.init", priority: 95, namespace: "outer" },
        { event: "TaskPlanningRail.init", priority: 90, namespace: "outer" },
      ],
    },
  }),
  fixtureNode({
    id: "rail-safety",
    kind: "rail",
    level: 4,
    owner: repository,
    label: "SafetyPromptRail",
    subtitle: "input guard",
    summary: "在输入进入 ReAct 前注入安全约束或发出控制信号。",
    repository,
    path: "openjiuwen/harness/rails/security/prompt_security_rail.py",
    position: { x: 20, y: 105 },
    renderer: "rail",
    expandable: true,
    attributes: {
      lifecycle: "runtime",
      hooks: [
        { event: "ON_USER_MESSAGE", priority: 85, namespace: "inner" },
        { event: "BEFORE_INVOKE", priority: 85, namespace: "outer" },
      ],
    },
  }),
  fixtureNode({
    id: "rail-context",
    kind: "rail",
    level: 4,
    owner: repository,
    label: "ContextAssembleRail",
    subtitle: "prompt mutation",
    summary: "在模型调用前组合提示词、工具与附加上下文。",
    repository,
    path: "openjiuwen/harness/rails/context_engineer/context_assemble_rail.py",
    position: { x: 480, y: 20 },
    renderer: "rail",
    expandable: true,
    attributes: {
      lifecycle: "runtime",
      hooks: [
        { event: "BEFORE_MODEL_CALL", priority: 85, namespace: "inner" },
        { event: "AFTER_MODEL_CALL", priority: 85, namespace: "inner" },
      ],
    },
  }),
  fixtureNode({
    id: "rail-retry",
    kind: "rail",
    level: 4,
    owner: repository,
    label: "LLMRetryRail",
    subtitle: "model recovery",
    summary: "捕获模型异常，依据重试策略恢复同一轮调用。",
    repository,
    path: "openjiuwen/core/single_agent/rail/base.py",
    symbol: "AgentRail",
    position: { x: 720, y: 20 },
    renderer: "rail",
    expandable: true,
    attributes: {
      lifecycle: "runtime",
      hooks: [
        { event: "ON_MODEL_EXCEPTION", priority: 70, namespace: "inner" },
        { event: "BEFORE_MODEL_CALL", priority: 70, namespace: "inner" },
      ],
    },
  }),
  fixtureNode({
    id: "rail-trajectory",
    kind: "rail",
    level: 4,
    owner: repository,
    label: "TrajectoryRail",
    subtitle: "iteration trace",
    summary: "记录每轮 ReAct 的决策、耗时与控制信号。",
    repository,
    path: "openjiuwen/harness/rails/evolution/trajectory_rail.py",
    position: { x: 960, y: 20 },
    renderer: "rail",
    expandable: true,
    attributes: {
      lifecycle: "runtime",
      hooks: [
        { event: "AFTER_REACT_ITERATION", priority: 10, namespace: "inner" },
        { event: "AFTER_INVOKE", priority: 10, namespace: "outer" },
      ],
    },
  }),
  fixtureNode({
    id: "rail-compression",
    kind: "rail",
    level: 4,
    owner: repository,
    label: "ContextProcessorRail",
    subtitle: "compress history",
    summary: "在上下文接近预算时压缩历史，并发布 compression_state。",
    repository,
    path: "openjiuwen/harness/rails/context_engineer/context_processor_rail.py",
    position: { x: 480, y: 510 },
    renderer: "rail",
    expandable: true,
    attributes: {
      lifecycle: "runtime",
      hooks: [
        { event: "BEFORE_MODEL_CALL", priority: 85, namespace: "inner" },
        { event: "context.compression_state", priority: 85, namespace: "inner" },
      ],
    },
  }),
  fixtureNode({
    id: "rail-tool",
    kind: "rail",
    level: 4,
    owner: repository,
    label: "ToolCallResilienceRail",
    subtitle: "tool boundary",
    summary: "包围工具调用，记录耗时、异常与恢复动作。",
    repository,
    path: "openjiuwen/harness/rails/tool_call_resilience_rail.py",
    position: { x: 720, y: 590 },
    renderer: "rail",
    expandable: true,
    attributes: {
      lifecycle: "runtime",
      hooks: [
        { event: "BEFORE_TOOL_CALL", priority: 70, namespace: "inner" },
        { event: "AFTER_TOOL_CALL", priority: 70, namespace: "inner" },
        { event: "ON_TOOL_EXCEPTION", priority: 70, namespace: "inner" },
      ],
    },
  }),
];

export const agentCoreEdges: readonly GraphEdgeRecord[] = [
  fixtureEdge({
    id: "e-deep-context",
    source: "react-loop",
    target: "context",
    kind: "causal",
    repository,
    path: "openjiuwen/core/single_agent/agents/react_agent.py",
  }),
  fixtureEdge({
    id: "e-context-model",
    source: "context",
    target: "model",
    kind: "causal",
    repository,
    path: "openjiuwen/core/single_agent/agents/react_agent.py",
  }),
  fixtureEdge({
    id: "e-model-decision",
    source: "model",
    target: "decision",
    kind: "causal",
    repository,
    path: "openjiuwen/core/single_agent/agents/react_agent.py",
  }),
  fixtureEdge({
    id: "e-decision-tool",
    source: "decision",
    target: "tool",
    sourceHandle: "flow-source-bottom",
    targetHandle: "flow-target-right",
    label: "tool_calls",
    kind: "causal",
    repository,
    path: "openjiuwen/core/single_agent/agents/react_agent.py",
  }),
  fixtureEdge({
    id: "e-tool-context",
    source: "tool",
    target: "context",
    sourceHandle: "flow-source-left",
    targetHandle: "flow-target-bottom",
    label: "observation",
    kind: "causal",
    repository,
    path: "openjiuwen/core/single_agent/agents/react_agent.py",
  }),
  fixtureEdge({
    id: "e-rail-init-deep",
    source: "rail-init",
    target: "deep-agent",
    sourceHandle: "rail-source-bottom",
    targetHandle: "rail-target-top",
    kind: "rail",
    repository,
    path: "openjiuwen/harness/deep_agent.py",
  }),
  fixtureEdge({
    id: "e-rail-context-context",
    source: "rail-context",
    target: "context",
    sourceHandle: "rail-source-bottom",
    targetHandle: "rail-target-top",
    kind: "rail",
    repository,
    path: "openjiuwen/harness/rails/context_engineer/context_assemble_rail.py",
  }),
  fixtureEdge({
    id: "e-rail-retry-model",
    source: "rail-retry",
    target: "model",
    sourceHandle: "rail-source-bottom",
    targetHandle: "rail-target-top",
    kind: "rail",
    repository,
    path: "openjiuwen/core/single_agent/rail/base.py",
  }),
  fixtureEdge({
    id: "e-rail-trajectory-decision",
    source: "rail-trajectory",
    target: "decision",
    sourceHandle: "rail-source-bottom",
    targetHandle: "rail-target-top",
    kind: "rail",
    repository,
    path: "openjiuwen/harness/rails/evolution/trajectory_rail.py",
  }),
  fixtureEdge({
    id: "e-rail-compression-context",
    source: "rail-compression",
    target: "context",
    sourceHandle: "rail-source-top",
    targetHandle: "flow-target-bottom",
    kind: "rail",
    repository,
    path: "openjiuwen/harness/rails/context_engineer/context_processor_rail.py",
  }),
  fixtureEdge({
    id: "e-rail-tool-tool",
    source: "rail-tool",
    target: "tool",
    sourceHandle: "rail-source-top",
    targetHandle: "flow-target-bottom",
    kind: "rail",
    repository,
    path: "openjiuwen/harness/rails/tool_call_resilience_rail.py",
  }),
];
