import type {
  RuntimeSubjectReference,
  RuntimeTraceRecording,
} from "../../../kernel";

const recordingId = "swarm-subagent-delegation-v1";
const modelRecordingId = `${recordingId}-model`;

const parentSubject: RuntimeSubjectReference = {
  id: "member:lead-developer",
  kind: "member",
  label: "Lead Developer",
  role: "leader",
  contextOwnerId: "ctx:lead-developer",
};

const subagentSubject: RuntimeSubjectReference = {
  id: "subagent:explore-auth",
  kind: "subagent",
  label: "Explore · auth paths",
  parentId: parentSubject.id,
  role: "explore_agent",
  contextOwnerId: "ctx:explore-auth",
};

const subagent = {
  invocationId: "subagent-invocation:explore-auth",
  subagentType: "explore_agent",
  dispatcher: "task-tool" as const,
  runMode: "foreground" as const,
  parentSessionId: "session:swarm-demo",
  sessionId: "session:swarm-demo_sub_explore_agent_a1b2c3d4",
  contextOwnerId: subagentSubject.contextOwnerId!,
  sessionPolicy: "ephemeral" as const,
  workspaceIsolation: "subdirectory" as const,
  toolPolicy: "configured" as const,
  toolCallSpanId: "span:task-tool",
};

const modelBase = {
  invocationId: "model:explore-auth:1",
  providerId: "demo.openai-compatible",
  modelId: "recorded-explorer-v1",
  source: "recording" as const,
  recordingId: modelRecordingId,
};

export const subagentDelegationRecording: RuntimeTraceRecording = {
  id: recordingId,
  owner: "jiuwenswarm",
  label: "Subagent isolated execution replay",
  description: "确定性展示 task_tool 派发、独立 session/context、内部 Rail/Model/Tool 与结果回填；不执行 Agent 或模型。",
  maxTokens: 8192,
  events: [
    {
      eventId: "subagent-demo-member-start",
      kind: "swarm.member",
      phase: "start",
      timestampMs: 0,
      spanId: "span:member",
      title: "Parent member starts",
      summary: "Swarm leader begins the parent run.",
      subject: parentSubject,
      payload: { status: "running" },
    },
    {
      eventId: "subagent-demo-parent-context",
      kind: "context.snapshot",
      phase: "instant",
      timestampMs: 20,
      spanId: "span:parent-context",
      parentSpanId: "span:member",
      title: "Parent context snapshot",
      subject: parentSubject,
      context: {
        operation: "replace",
        ownerId: parentSubject.contextOwnerId,
        messages: [{
          id: "parent-user",
          role: "user",
          label: "Parent request",
          raw: "Inspect the authentication changes, but keep broad repository exploration outside the parent context.",
          preview: "Inspect authentication changes; delegate broad exploration.",
          tokens: 20,
          source: "team.message",
        }],
      },
      token: { used: 20, delta: 20, budget: 8192 },
    },
    {
      eventId: "subagent-demo-parent-tools",
      kind: "ability.register",
      phase: "instant",
      timestampMs: 34,
      spanId: "span:parent-tool-registry",
      parentSpanId: "span:member",
      title: "Parent tool schema registered",
      summary: "The parent model can see the fixed task_tool schema.",
      subject: parentSubject,
      details: [
        { label: "tool", value: "task_tool" },
        { label: "policy", value: "fixed-parent-profile" },
      ],
      payload: { tools: ["task_tool"], policy: "fixed-parent-profile" },
      definition: {
        repository: "agent-core",
        path: "openjiuwen/core/agent/ability_manager.py",
        symbol: "AbilityManager",
      },
    },
    {
      eventId: "subagent-demo-dispatch-start",
      kind: "tool.call",
      phase: "start",
      timestampMs: 48,
      spanId: "span:task-tool",
      parentSpanId: "span:member",
      title: "task_tool dispatches explore_agent",
      summary: "Parent invokes the built-in Subagent dispatcher.",
      subject: parentSubject,
      payload: {
        toolName: "task_tool",
        subagentType: "explore_agent",
        background: false,
        arguments: {
          subagent_type: "explore_agent",
          task_description: "Find the authentication branches changed by the current work and report their call path.",
        },
      },
      definition: {
        repository: "agent-core",
        path: "openjiuwen/harness/tools/subagent/task_tool.py",
        symbol: "TaskTool.invoke",
      },
    },
    {
      eventId: "subagent-demo-start",
      kind: "swarm.subagent",
      phase: "start",
      timestampMs: 60,
      spanId: "span:subagent",
      parentSpanId: "span:task-tool",
      title: "Explore Subagent starts",
      summary: "A fresh DeepAgent starts in an isolated session and Context owner.",
      subject: subagentSubject,
      subagent,
      definition: {
        repository: "agent-core",
        path: "openjiuwen/harness/tools/subagent/task_tool.py",
        symbol: "TaskTool.invoke",
      },
      payload: { status: "running" },
    },
    {
      eventId: "subagent-demo-context",
      kind: "context.snapshot",
      phase: "instant",
      timestampMs: 74,
      spanId: "span:subagent-context",
      parentSpanId: "span:subagent",
      title: "Subagent context is created",
      summary: "Only the delegated contract and task enter the child window.",
      subject: subagentSubject,
      context: {
        operation: "replace",
        ownerId: subagentSubject.contextOwnerId,
        messages: [
          {
            id: "subagent-system",
            role: "system",
            label: "Explore contract",
            raw: "Search read-only. Return concrete file and symbol evidence. Do not modify repository files.",
            preview: "Read-only exploration with file-level evidence.",
            tokens: 18,
            source: "subagent.session",
          },
          {
            id: "subagent-task",
            role: "user",
            label: "Delegated task",
            raw: "Find the authentication branches changed by the current work and report their call path.",
            preview: "Find changed authentication branches and call paths.",
            tokens: 22,
            source: "subagent.task",
          },
        ],
      },
      token: { used: 40, delta: 40, budget: 4096 },
    },
    {
      eventId: "subagent-demo-child-tools",
      kind: "ability.register",
      phase: "instant",
      timestampMs: 84,
      spanId: "span:subagent-tool-registry",
      parentSpanId: "span:subagent",
      title: "Child read-only tools registered",
      summary: "Only the configured GrepTool schema enters the child model call.",
      subject: subagentSubject,
      details: [
        { label: "tool", value: "GrepTool" },
        { label: "policy", value: "fixed-subagent-profile" },
      ],
      payload: { tools: ["GrepTool"], policy: "fixed-subagent-profile" },
      definition: {
        repository: "agent-core",
        path: "openjiuwen/core/agent/ability_manager.py",
        symbol: "AbilityManager",
      },
    },
    {
      eventId: "subagent-demo-agent-start",
      kind: "agent.invoke",
      phase: "start",
      timestampMs: 92,
      spanId: "span:subagent-agent",
      parentSpanId: "span:subagent",
      title: "Child DeepAgent invoke",
      summary: "The Subagent starts its own Agent/ReAct boundary.",
      subject: subagentSubject,
    },
    {
      eventId: "subagent-demo-before-model",
      kind: "rail.hook",
      phase: "instant",
      timestampMs: 110,
      spanId: "span:subagent-rail",
      parentSpanId: "span:subagent-agent",
      title: "Subagent Rail reviews model input",
      subject: subagentSubject,
      hook: {
        rail: "ObservabilityRail",
        callback: "BEFORE_MODEL_CALL",
        priority: 20,
        namespace: "inner",
        durationMs: 2,
        mutationDiff: "no changes",
        controlSignal: "continue",
        noop: true,
        exact: true,
        examines: ["ModelCallInputs.messages", "context.ownerId"],
      },
    },
    {
      eventId: "subagent-demo-model-start",
      kind: "model.call",
      phase: "start",
      timestampMs: 126,
      spanId: "span:subagent-model",
      parentSpanId: "span:subagent-agent",
      title: "Explore model call",
      subject: subagentSubject,
      model: { ...modelBase, recordingSequence: 0 },
    },
    {
      eventId: "subagent-demo-model-stream",
      kind: "model.stream",
      phase: "instant",
      timestampMs: 150,
      spanId: "span:subagent-model",
      parentSpanId: "span:subagent-agent",
      title: "Recorded reasoning delta",
      subject: subagentSubject,
      model: {
        ...modelBase,
        recordingSequence: 1,
        delta: "I will inspect the authentication entry points and their callers.",
      },
    },
    {
      eventId: "subagent-demo-model-usage",
      kind: "model.usage",
      phase: "instant",
      timestampMs: 166,
      spanId: "span:subagent-model",
      parentSpanId: "span:subagent-agent",
      title: "Subagent model usage",
      subject: subagentSubject,
      model: {
        ...modelBase,
        recordingSequence: 2,
        usage: {
          inputTokens: 40,
          outputTokens: 9,
          totalTokens: 49,
          reasoningTokens: 6,
        },
      },
      token: { used: 49, delta: 9, budget: 4096 },
    },
    {
      eventId: "subagent-demo-model-end",
      kind: "model.call",
      phase: "end",
      timestampMs: 178,
      durationMs: 52,
      spanId: "span:subagent-model",
      parentSpanId: "span:subagent-agent",
      title: "Explore model selects grep",
      subject: subagentSubject,
      model: {
        ...modelBase,
        recordingSequence: 3,
        responseText: "Search auth handlers and resolve their callers.",
        finishReason: "tool_call",
      },
    },
    {
      eventId: "subagent-demo-tool-start",
      kind: "tool.call",
      phase: "start",
      timestampMs: 194,
      spanId: "span:subagent-grep",
      parentSpanId: "span:subagent-agent",
      title: "Subagent calls GrepTool",
      summary: "Read-only search runs inside the Subagent tool policy.",
      subject: subagentSubject,
      payload: {
        toolName: "GrepTool",
        query: "authenticate|authorization",
        arguments: { query: "authenticate|authorization", path: "openjiuwen" },
      },
      definition: {
        repository: "agent-core",
        path: "openjiuwen/harness/tools/filesystem.py",
        symbol: "GrepTool.invoke",
      },
    },
    {
      eventId: "subagent-demo-tool-end",
      kind: "tool.call",
      phase: "end",
      timestampMs: 222,
      durationMs: 28,
      spanId: "span:subagent-grep",
      parentSpanId: "span:subagent-agent",
      title: "GrepTool returns evidence",
      summary: "Three authentication symbols are returned to the child Agent.",
      subject: subagentSubject,
      payload: {
        toolName: "GrepTool",
        resultCount: 3,
        status: "completed",
        result: {
          symbols: [
            "auth_router.authenticate",
            "token_guard.authorize",
            "session_policy.validate",
          ],
          resultCount: 3,
        },
      },
    },
    {
      eventId: "subagent-demo-observation",
      kind: "context.delta",
      phase: "instant",
      timestampMs: 236,
      spanId: "span:subagent-observation",
      parentSpanId: "span:subagent-agent",
      title: "Tool evidence enters child Context",
      subject: subagentSubject,
      context: {
        operation: "append",
        ownerId: subagentSubject.contextOwnerId,
        messages: [{
          id: "subagent-tool-result",
          role: "tool",
          label: "GrepTool observation",
          raw: "Found auth_router.authenticate, token_guard.authorize, and session_policy.validate with their source paths.",
          preview: "Found three authentication symbols with source paths.",
          tokens: 16,
          source: "tool:GrepTool",
        }],
      },
      token: { used: 65, delta: 16, tool: 16, budget: 4096 },
    },
    {
      eventId: "subagent-demo-agent-end",
      kind: "agent.invoke",
      phase: "end",
      timestampMs: 258,
      durationMs: 166,
      spanId: "span:subagent-agent",
      parentSpanId: "span:subagent",
      title: "Child DeepAgent completes",
      summary: "The isolated run returns only its final evidence summary.",
      subject: subagentSubject,
    },
    {
      eventId: "subagent-demo-end",
      kind: "swarm.subagent",
      phase: "end",
      timestampMs: 270,
      durationMs: 210,
      spanId: "span:subagent",
      parentSpanId: "span:task-tool",
      title: "Explore Subagent completes",
      summary: "The Subagent result crosses back through task_tool.",
      subject: subagentSubject,
      subagent: {
        ...subagent,
        resultPreview: "Returned three authentication symbols and their caller paths.",
      },
      payload: { status: "completed" },
    },
    {
      eventId: "subagent-demo-dispatch-end",
      kind: "tool.call",
      phase: "end",
      timestampMs: 282,
      durationMs: 234,
      spanId: "span:task-tool",
      parentSpanId: "span:member",
      title: "task_tool returns",
      summary: "Only the final Subagent output is returned to the parent.",
      subject: parentSubject,
      payload: {
        toolName: "task_tool",
        status: "completed",
        result: {
          subagentType: "explore_agent",
          evidenceCount: 3,
          summary: "Returned three authentication symbols and their caller paths.",
        },
      },
    },
    {
      eventId: "subagent-demo-parent-result",
      kind: "context.delta",
      phase: "instant",
      timestampMs: 296,
      spanId: "span:parent-result",
      parentSpanId: "span:member",
      title: "Result enters parent Context",
      summary: "The child window remains isolated; only its final answer is appended.",
      subject: parentSubject,
      context: {
        operation: "append",
        ownerId: parentSubject.contextOwnerId,
        messages: [{
          id: "parent-subagent-result",
          role: "tool",
          label: "Explore Subagent result",
          raw: "The changed authentication path covers auth_router.authenticate, token_guard.authorize, and session_policy.validate; callers were included as file-level evidence.",
          preview: "Subagent returned three authentication symbols and callers.",
          tokens: 24,
          source: "subagent:explore_agent",
        }],
      },
      token: { used: 44, delta: 24, tool: 24, budget: 8192 },
    },
    {
      eventId: "subagent-demo-member-end",
      kind: "swarm.member",
      phase: "end",
      timestampMs: 320,
      durationMs: 320,
      spanId: "span:member",
      title: "Parent member completes",
      subject: parentSubject,
      payload: { status: "completed" },
    },
    {
      eventId: "subagent-demo-trace-end",
      kind: "trace.status",
      phase: "end",
      timestampMs: 330,
      spanId: "span:trace",
      title: "Subagent replay complete",
      summary: "All events came from a deterministic recording.",
    },
  ],
};
