import type { ModelRuntimeRecording } from "../../../kernel";

const provider = "demo.openai-compatible";
const model = "recorded-reasoner-v1";
const recordingId = "model-provider-v1-stream-and-cancel";

export const streamAndCancelRecording: ModelRuntimeRecording = {
  id: recordingId,
  label: "Model Provider deterministic replay",
  description: "一段完成的流式调用与一段显式取消调用；不访问任何模型 API。",
  maxTokens: 8192,
  events: [
    {
      eventId: "provider-demo-agent-start",
      kind: "agent.invoke",
      phase: "start",
      timestampMs: 0,
      spanId: "span-agent",
      title: "Replay agent starts",
      summary: "开始重放已归一化的 Provider 事件。",
    },
    {
      eventId: "provider-demo-context",
      kind: "context.snapshot",
      phase: "instant",
      timestampMs: 16,
      spanId: "span-context",
      parentSpanId: "span-agent",
      title: "Recorded request context",
      token: { used: 31, delta: 31, budget: 8192 },
      context: {
        operation: "replace",
        messages: [
          {
            id: "provider-system",
            role: "system",
            label: "Replay policy",
            raw: "Summarize the request and never execute external tools during recording replay.",
            preview: "Summarize the request; recording replay cannot execute tools.",
            tokens: 14,
            source: "model.recording",
          },
          {
            id: "provider-user",
            role: "user",
            label: "Recorded user request",
            raw: "Draft a safe acknowledgement for dev@example.com using reference sk-demo-1234567890.",
            preview: "Draft a safe acknowledgement for [email] using a hidden reference.",
            tokens: 17,
            source: "model.recording",
          },
        ],
      },
    },
    {
      eventId: "provider-demo-call-1-start",
      kind: "model.call",
      phase: "start",
      timestampMs: 42,
      spanId: "span-model-1",
      parentSpanId: "span-agent",
      title: "Primary model request",
      model: {
        invocationId: "model-invocation-1",
        providerId: provider,
        modelId: model,
        source: "recording",
        recordingId,
        recordingSequence: 0,
        budget: {
          maxOutputTokens: 96,
          maxTotalTokens: 160,
          maxCostMicros: 5000,
          currency: "USD",
        },
      },
    },
    {
      eventId: "provider-demo-call-1-delta-1",
      kind: "model.stream",
      phase: "instant",
      timestampMs: 74,
      spanId: "span-model-1",
      parentSpanId: "span-agent",
      title: "Stream delta 1",
      model: {
        invocationId: "model-invocation-1",
        providerId: provider,
        modelId: model,
        source: "recording",
        recordingId,
        recordingSequence: 1,
        delta: "I can prepare a safe acknowledgement for ",
      },
    },
    {
      eventId: "provider-demo-call-1-delta-2",
      kind: "model.stream",
      phase: "instant",
      timestampMs: 101,
      spanId: "span-model-1",
      parentSpanId: "span-agent",
      title: "Stream delta 2",
      model: {
        invocationId: "model-invocation-1",
        providerId: provider,
        modelId: model,
        source: "recording",
        recordingId,
        recordingSequence: 2,
        delta: "dev@example.com without exposing sk-demo-1234567890.",
      },
    },
    {
      eventId: "provider-demo-call-1-usage",
      kind: "model.usage",
      phase: "instant",
      timestampMs: 116,
      spanId: "span-model-1",
      parentSpanId: "span-agent",
      title: "Primary usage",
      token: { used: 45, delta: 14, budget: 8192 },
      model: {
        invocationId: "model-invocation-1",
        providerId: provider,
        modelId: model,
        source: "recording",
        recordingId,
        recordingSequence: 3,
        usage: {
          inputTokens: 31,
          outputTokens: 14,
          totalTokens: 45,
          cachedInputTokens: 8,
          reasoningTokens: 4,
          costMicros: 1260,
          currency: "USD",
        },
      },
    },
    {
      eventId: "provider-demo-call-1-end",
      kind: "model.call",
      phase: "end",
      timestampMs: 132,
      durationMs: 90,
      spanId: "span-model-1",
      parentSpanId: "span-agent",
      title: "Primary model complete",
      model: {
        invocationId: "model-invocation-1",
        providerId: provider,
        modelId: model,
        source: "recording",
        recordingId,
        recordingSequence: 4,
        responseText: "I can prepare a safe acknowledgement for dev@example.com without exposing sk-demo-1234567890.",
        finishReason: "stop",
      },
    },
    {
      eventId: "provider-demo-call-2-start",
      kind: "model.call",
      phase: "start",
      timestampMs: 166,
      spanId: "span-model-2",
      parentSpanId: "span-agent",
      title: "Optional follow-up request",
      model: {
        invocationId: "model-invocation-2",
        providerId: provider,
        modelId: model,
        source: "recording",
        recordingId,
        recordingSequence: 5,
        budget: {
          maxOutputTokens: 64,
          maxTotalTokens: 128,
          maxCostMicros: 3000,
          currency: "USD",
        },
      },
    },
    {
      eventId: "provider-demo-call-2-delta",
      kind: "model.stream",
      phase: "instant",
      timestampMs: 191,
      spanId: "span-model-2",
      parentSpanId: "span-agent",
      title: "Follow-up partial output",
      model: {
        invocationId: "model-invocation-2",
        providerId: provider,
        modelId: model,
        source: "recording",
        recordingId,
        recordingSequence: 6,
        delta: "Preparing an optional expanded response…",
      },
    },
    {
      eventId: "provider-demo-call-2-usage",
      kind: "model.usage",
      phase: "instant",
      timestampMs: 204,
      spanId: "span-model-2",
      parentSpanId: "span-agent",
      title: "Follow-up partial usage",
      token: { used: 52, delta: 7, budget: 8192 },
      model: {
        invocationId: "model-invocation-2",
        providerId: provider,
        modelId: model,
        source: "recording",
        recordingId,
        recordingSequence: 7,
        usage: {
          inputTokens: 31,
          outputTokens: 7,
          totalTokens: 38,
          costMicros: 860,
          currency: "USD",
        },
      },
    },
    {
      eventId: "provider-demo-call-2-cancel",
      kind: "model.cancel",
      phase: "instant",
      timestampMs: 218,
      spanId: "span-model-2",
      parentSpanId: "span-agent",
      title: "Follow-up cancelled",
      model: {
        invocationId: "model-invocation-2",
        providerId: provider,
        modelId: model,
        source: "recording",
        recordingId,
        recordingSequence: 8,
        cancelReason: "operator_stop_after_primary_answer",
      },
    },
    {
      eventId: "provider-demo-agent-end",
      kind: "agent.invoke",
      phase: "end",
      timestampMs: 236,
      durationMs: 236,
      spanId: "span-agent",
      title: "Replay agent completes",
      summary: "录制回放完成；没有执行真实 Provider 请求。",
    },
    {
      eventId: "provider-demo-trace-end",
      kind: "trace.status",
      phase: "end",
      timestampMs: 240,
      spanId: "span-trace",
      title: "Recording replay complete",
    },
  ],
};
