import type {
  RailNodeDefinition,
  StageNodeDefinition,
  TraceEdgeDefinition,
} from "../../types/trace";

const stageNodes: StageNodeDefinition[] = [
  {
    id: "input",
    type: "stage",
    position: { x: 20, y: 280 },
    label: "Swarm Ingress",
    subtitle: "request + session ingress",
    kind: "input",
    description: "JiuwenSwarm 接收用户输入与会话信息，再把请求交给 Agent Core 运行时。",
    sourceLocation: "jiuwenswarm/server/agent_ws_server.py",
    owner: "jiuwenswarm",
  },
  {
    id: "deep-agent",
    type: "stage",
    position: { x: 250, y: 280 },
    label: "DeepAgent",
    subtitle: "outer orchestration",
    kind: "agent",
    description: "外层 Agent 生命周期，负责 invoke、任务编排与会话收尾。",
    sourceLocation: "openjiuwen/harness/deep_agent.py",
    owner: "agent-core",
  },
  {
    id: "react-loop",
    type: "stage",
    position: { x: 40, y: 110 },
    label: "ReActAgent",
    subtitle: "inner loop controller",
    kind: "loop",
    description:
      "DeepAgent 内部的 ReAct 循环控制器，负责组织 Context、模型决策、工具 observation 与下一轮迭代。",
    sourceLocation: "openjiuwen/core/single_agent/agents/react_agent.py",
    owner: "agent-core",
    accent: "signal",
  },
  {
    id: "context",
    type: "stage",
    position: { x: 480, y: 280 },
    label: "Context Engine",
    subtitle: "assemble window",
    kind: "context",
    description: "组合 system、history、tool schema，并输出最终 ContextWindow。",
    sourceLocation: "openjiuwen/core/context_engine/base.py",
    owner: "agent-core",
    accent: "context",
  },
  {
    id: "model",
    type: "stage",
    position: { x: 720, y: 155 },
    label: "Model Call",
    subtitle: "reason + generate",
    kind: "model",
    description: "向模型发送最终上下文，接收文本或 tool_calls。",
    sourceLocation: "openjiuwen/core/single_agent/agents/react_agent.py",
    owner: "agent-core",
    accent: "signal",
  },
  {
    id: "decision",
    type: "stage",
    position: { x: 960, y: 280 },
    label: "ReAct Decision",
    subtitle: "route next action",
    kind: "decision",
    description: "判断模型结果是结束响应、执行工具，还是进入下一轮 ReAct。",
    sourceLocation: "openjiuwen/core/single_agent/agents/react_agent.py",
    owner: "agent-core",
  },
  {
    id: "tool",
    type: "stage",
    position: { x: 720, y: 440 },
    label: "Tool Runtime",
    subtitle: "execute + observe",
    kind: "tool",
    description: "执行工具调用，并把 observation 追加回上下文。",
    sourceLocation: "openjiuwen/core/single_agent/ability_manager.py",
    owner: "agent-core",
  },
  {
    id: "output",
    type: "stage",
    position: { x: 1200, y: 280 },
    label: "Swarm Response",
    subtitle: "stream + persist",
    kind: "output",
    description: "JiuwenSwarm 接收 Agent Core 的最终结果，完成流式响应与会话持久化。",
    sourceLocation: "jiuwenswarm/server/agent_ws_server.py",
    owner: "jiuwenswarm",
    accent: "signal",
  },
];

const railNodes: RailNodeDefinition[] = [
  {
    id: "rail-init",
    type: "rail",
    position: { x: 250, y: 20 },
    label: "Rail lifecycle",
    subtitle: "init / uninit",
    description: "独立于运行 Hook 的初始化组；按优先级注册 Rail。",
    sourceLocation: "openjiuwen/harness/deep_agent.py",
    owner: "agent-core",
    lifecycle: "init",
    hooks: [
      { event: "SysOperationRail.init", priority: 100, namespace: "outer" },
      { event: "SkillUseRail.init", priority: 95, namespace: "outer" },
      { event: "TaskPlanningRail.init", priority: 90, namespace: "outer" },
    ],
  },
  {
    id: "rail-safety",
    type: "rail",
    position: { x: 20, y: 105 },
    label: "SafetyPromptRail",
    subtitle: "input guard",
    description: "在输入进入 ReAct 前注入安全约束或发出控制信号。",
    sourceLocation: "openjiuwen/harness/rails/security/prompt_security_rail.py",
    owner: "agent-core",
    hooks: [
      { event: "ON_USER_MESSAGE", priority: 85, namespace: "inner" },
      { event: "BEFORE_INVOKE", priority: 85, namespace: "outer" },
    ],
  },
  {
    id: "rail-context",
    type: "rail",
    position: { x: 480, y: 20 },
    label: "ContextAssembleRail",
    subtitle: "prompt mutation",
    description: "在模型调用前组合提示词、工具与附加上下文。",
    sourceLocation: "openjiuwen/harness/rails/context_engineer/context_assemble_rail.py",
    owner: "agent-core",
    hooks: [
      { event: "BEFORE_MODEL_CALL", priority: 85, namespace: "inner" },
      { event: "AFTER_MODEL_CALL", priority: 85, namespace: "inner" },
    ],
  },
  {
    id: "rail-retry",
    type: "rail",
    position: { x: 720, y: 20 },
    label: "LLMRetryRail",
    subtitle: "model recovery",
    description: "捕获模型异常，依据重试策略恢复同一轮调用。",
    sourceLocation: "openjiuwen/core/single_agent/rail/base.py",
    owner: "agent-core",
    hooks: [
      { event: "ON_MODEL_EXCEPTION", priority: 70, namespace: "inner" },
      { event: "BEFORE_MODEL_CALL", priority: 70, namespace: "inner" },
    ],
  },
  {
    id: "rail-trajectory",
    type: "rail",
    position: { x: 960, y: 20 },
    label: "TrajectoryRail",
    subtitle: "iteration trace",
    description: "记录每轮 ReAct 的决策、耗时与控制信号。",
    sourceLocation: "openjiuwen/harness/rails/evolution/trajectory_rail.py",
    owner: "agent-core",
    hooks: [
      { event: "AFTER_REACT_ITERATION", priority: 10, namespace: "inner" },
      { event: "AFTER_INVOKE", priority: 10, namespace: "outer" },
    ],
  },
  {
    id: "rail-compression",
    type: "rail",
    position: { x: 480, y: 510 },
    label: "ContextProcessorRail",
    subtitle: "compress history",
    description: "在上下文接近预算时压缩历史，并发布 compression_state。",
    sourceLocation: "openjiuwen/harness/rails/context_engineer/context_processor_rail.py",
    owner: "agent-core",
    hooks: [
      { event: "BEFORE_MODEL_CALL", priority: 85, namespace: "inner" },
      { event: "context.compression_state", priority: 85, namespace: "inner" },
    ],
  },
  {
    id: "rail-tool",
    type: "rail",
    position: { x: 720, y: 590 },
    label: "ToolCallResilienceRail",
    subtitle: "tool boundary",
    description: "包围工具调用，记录耗时、异常与恢复动作。",
    sourceLocation: "openjiuwen/harness/rails/tool_call_resilience_rail.py",
    owner: "agent-core",
    hooks: [
      { event: "BEFORE_TOOL_CALL", priority: 70, namespace: "inner" },
      { event: "AFTER_TOOL_CALL", priority: 70, namespace: "inner" },
      { event: "ON_TOOL_EXCEPTION", priority: 70, namespace: "inner" },
    ],
  },
];

export const graphNodes = [...stageNodes, ...railNodes];

export const graphEdges: TraceEdgeDefinition[] = [
  { id: "e-input-deep", source: "input", target: "deep-agent", kind: "causal" },
  { id: "e-deep-context", source: "react-loop", target: "context", kind: "causal" },
  { id: "e-context-model", source: "context", target: "model", kind: "causal" },
  { id: "e-model-decision", source: "model", target: "decision", kind: "causal" },
  {
    id: "e-decision-tool",
    source: "decision",
    target: "tool",
    sourceHandle: "flow-source-bottom",
    targetHandle: "flow-target-right",
    label: "tool_calls",
    kind: "causal",
  },
  {
    id: "e-tool-context",
    source: "tool",
    target: "context",
    sourceHandle: "flow-source-left",
    targetHandle: "flow-target-bottom",
    label: "observation",
    kind: "causal",
  },
  {
    id: "e-decision-output",
    source: "decision",
    target: "output",
    label: "final",
    kind: "causal",
  },
  { id: "e-rail-init-deep", source: "rail-init", target: "deep-agent", sourceHandle: "rail-source-bottom", targetHandle: "rail-target-top", kind: "rail" },
  { id: "e-rail-safety-input", source: "rail-safety", target: "input", sourceHandle: "rail-source-bottom", targetHandle: "rail-target-top", kind: "rail" },
  { id: "e-rail-context-context", source: "rail-context", target: "context", sourceHandle: "rail-source-bottom", targetHandle: "rail-target-top", kind: "rail" },
  { id: "e-rail-retry-model", source: "rail-retry", target: "model", sourceHandle: "rail-source-bottom", targetHandle: "rail-target-top", kind: "rail" },
  {
    id: "e-rail-trajectory-decision",
    source: "rail-trajectory",
    target: "decision",
    sourceHandle: "rail-source-bottom",
    targetHandle: "rail-target-top",
    kind: "rail",
  },
  {
    id: "e-rail-compression-context",
    source: "rail-compression",
    target: "context",
    sourceHandle: "rail-source-top",
    targetHandle: "flow-target-bottom",
    kind: "rail",
  },
  { id: "e-rail-tool-tool", source: "rail-tool", target: "tool", sourceHandle: "rail-source-top", targetHandle: "flow-target-bottom", kind: "rail" },
];

